custom_components/ocpp/sensor.py

@lbbrhzn, these are the last changes I was going to make while you're working on the structure.

ocpp: handle unit conversion to kW, kWh

---

custom_components/ocpp/api.py

Hi @lbbrhzn, this function can be used for a custom service call when ready as referred to in #34

ocpp: add update firmware function

---

custom_components/ocpp/api.py
custom_components/ocpp/const.py

I've replaced measurand names with the constants provided by ocpp.v16.enums.Measurand.
Ideally, I would like to make api.py string literal free, this will make linting much more effective.
Currently you can only detect runtime if you've make an error in one of the strings...

Use enums for measurands

---

custom_components/ocpp/const.py

@lbbrhzn, not sure why but the enums need to be explicitly converted to strings to work

ocpp: bug fix use enums for measurands

---

.github/workflows/constraints.txt

Revert "build(deps): bump sqlalchemy from 1.4.17 to 1.4.21 in /.github/workflows"

---

custom_components/ocpp/api.py

Switched to presenting overall current,  rather than average phase current for consistency between single and 3 phase chargers, so that overall charger real power = power.factor x current.import x voltage.

Update current for 3 phase charger

---

custom_components/ocpp/api.py
custom_components/ocpp/enums.py

Fixes #78 using same approach as HA supported_features attribute

Change supported features to using flags

---

custom_components/ocpp/api.py
custom_components/ocpp/enums.py

This can be used to understand whether there may underlying network issues causing ocpp integration to become erratic/unstable

New metric added to track websocket Reconnects

---

custom_components/ocpp/api.py
tests/test_charge_point.py

Fixes #148, maximum charge rate to be set by maximum_current slider only

Remove setting charging profile from start_transaction

---

custom_components/ocpp/api.py

to avoid a websocket half-close which results in the charger staying connected whilst the server thinks it is disconnected see https://www.excentis.com/blog/tcp-half-close-cool-feature-now-broken
https://github.com/eclipse/jetty.project/issues/3671

add close_timeout

---

custom_components/ocpp/api.py

@lbbrhzn , suggest moving to 10 it improves handling of handshake and closing eg addresses a half close situation

Fix websockets 10 test error

---

custom_components/ocpp/api.py
custom_components/ocpp/enums.py

data.response and config.response metrics to store reponses returned from charger for use in automations/templating

New metrics

---

custom_components/ocpp/api.py

Hopefully stops integration responding to the charger when there has been a websocket half-close, allowing charger to timeout websocket and reconnect

Set connection to None on disconnect

---

custom_components/ocpp/api.py

A charger can drop messages from the server until a valid boot notification response is received, so send acceptance before doing anything else. @lbbrhzn the heartbeat interval could be set in the config flow as the default for my charger is 12h or 43200 but others don't accept such a long interval.

Optimise boot notification, set heartbeat to hourly

---

custom_components/ocpp/api.py

The OCPP reference guide specifies:
* Current.Export Instantaneous current flow from EV
* Current.Import Instantaneous current flow to EV
My Grizzl-E Smart EVSE actually sends the data points in the reverse direction (go figure, but the integration still works https://github.com/lbbrhzn/ocpp/issues/224 ) and does not send any additionnal Current.* samples after the EVSE reports the Suspend event.
``` 
[2,"4011002226dbd69865","MeterValues",{"connectorId":1,"meterValue":[{"timestamp":"2021-12-13T11:04:52.001Z","sampledValue":[{"measurand":"Current.Export","unit":"A","value":"28.00"}]}],"transactionId":1639405855}]
[2,"401100222689a1664a","MeterValues",{"connectorId":1,"meterValue":[{"timestamp":"2021-12-13T11:06:52.001Z","sampledValue":[{"measurand":"Current.Export","unit":"A","value":"27.79 …
```

Upon Suspend events, energy flow is assumed to be 0 in both directions

---

custom_components/ocpp/button.py
custom_components/ocpp/const.py
custom_components/ocpp/switch.py
requirements_dev.txt
tests/test_charge_point.py

@lbbrhzn, I can't test on a live system at the moment. If you're able to on your charger before merging that'd be great.

Use button entity for pulse switches

---

custom_components/ocpp/api.py
custom_components/ocpp/button.py
custom_components/ocpp/const.py
custom_components/ocpp/enums.py
custom_components/ocpp/sensor.py
tests/test_charge_point.py

includes: 
- setting scale (how many dp) for metrics and handling dp formatting in sensor
- fix for #220

Refactor Sensors for 2021.12+

---

custom_components/ocpp/api.py
custom_components/ocpp/manifest.json
tests/conftest.py

Charger errors reported as a persistent notification eg Unsupported, Rejected to alert users the request via the integration has failed.

Add notifications for charger errors

---

custom_components/ocpp/api.py
custom_components/ocpp/config_flow.py
custom_components/ocpp/const.py
custom_components/ocpp/translations/en.json
custom_components/ocpp/translations/i-default.json

This PR adds regular sampling of the meter when it is not charging (ie idle) to the integration configuration. @lbbrhzn please add the Dutch translation

Add sampling config of meter when idle

---

custom_components/ocpp/api.py

add defaults for all entry data. This is especially useful when upgrading, preventing the need to reconfigure.

add defaults for entry.data

---

custom_components/ocpp/api.py

for chargers that are incompatible with the ChargePointMaxProfile see #221

add TxDefaultProfile to set charging rate

---

custom_components/ocpp/api.py
tests/test_charge_point.py

@lbbrhzn I think it is best for the latency function not to close the connection or manage unexpected connection exceptions (leaving the main charger routine to do this), also if it does timeout to still log the 20000ms latency time.

tweak latency function

---

.devcontainer/configuration.yaml
custom_components/ocpp/api.py

after adding trigger_boot_notification to post_connect, we could get into an infinite loop because the boot notification handler would create a new post_connect. This makes sense in case of a spontaneous reboot, but not if the boot notification was triggered. So we check for this, and only only re-do post connect if the boot notification was not triggered.

improve reconnect and trigger boot notification

---

custom_components/ocpp/api.py

my charger is not ready to respond/discards the first ping and so goes into a reconnect loop

add delay at start of monitor

---

custom_components/ocpp/api.py
custom_components/ocpp/enums.py

add sensor for id_tag

---

custom_components/ocpp/switch.py

use connector status for charging switch

---

custom_components/ocpp/api.py
tests/test_charge_point.py

Handle unknown key in configure

---

custom_components/ocpp/api.py

use the ZULU datetime format in the ocpp communication
https://github.com/lbbrhzn/ocpp/issues/512

Update api.py: use the ZULU datetime format in OCPP

---

custom_components/ocpp/__init__.py
custom_components/ocpp/api.py

I've notice my log contains a lot of information regarding OCPP
This PR suggest to reduce the amount of logs for a regular HA
environment.

update default logger to INFO

---

.github/workflows/publish.yml
README.md
hacs.json
manage/update_manifest.py

followed HACS approach to creating zip asset on publish so that downloads can be tracked https://github.com/hacs/integration

Track downloads, update manifest on publish

---

docs/supported-devices.md
docs/user-guide.md

After testing the latest OCPP server (v 0.4.36) with my Grizzl-E charger, I'm happy to report that it substantially works. There are some quirks of the Grizzl-E charger and workarounds needed for it to play nice with the OCPP server.  I'm proposing some additions to the Documentation to record these details. 
Two files are affected: **supported-devices.md** and **user-guide.md**
Let me know if you'd like any changes to this PR.  For instance, do you prefer multiple commits to be rebased into one?  Thanks!

Add United Chargers Grizzl-E to documentation

---

docs/supported-devices.md

Add a link to a getting started guide for connecting CTEK Chargestorm Connected 2.

Add link to getting started guide for CTEK

---

docs/user-guide.md

Added recommended entities working with Vestel EVC-04 series

Add Recommendation for Vestel EVC-04 Wallboxes

---

custom_components/ocpp/api.py

Some charges seem to add spaces in profiles name, instead of using CamelCase naming:
`2023-02-11 12:16:38.236 INFO (MainThread) [ocpp] 31457413209719: receive message [3,"521ee108-e7db-4e43-8288-422477c630cb",{"configurationKey":[{"key":"SupportedFeatureProfiles","value":"Core,Local Auth List Management,Reservation,Smart Charging,Remote Trigger","readonly":true}]}]`
This PR adds support for that

Add support for spaces in returned profiles

---

custom_components/ocpp/api.py
requirements_dev.txt
tests/test_charge_point.py

Added detection between session and main meter energy values as discussed in #366.
According to OCPP spec, if there is a transaction id the values are for that session and if there is no transaction id the values are from main meter. For example ABB Terra AC sends separate energy used for the session and the charger lifetime energy usage.
Now if there is a transaction id with the energy value, it is saved to entity "xxx.Session" (example: "Energy.Active.Import.Register.Session")
If there is no transaction id with the energy value, it is saved to entity "xxx" (example: ""Energy.Active.Import.Register)
This way the energy values between the sessions and main meters are kept separated so that they don't mix in the homeassistant history and graphs. Also, if the charger gives the energy used …

Added detection between session and main meter energy values

---

custom_components/ocpp/api.py
tests/test_charge_point.py

Fix for issues discussed in end of #919

bugfix meter value logic

---

custom_components/ocpp/switch.py

remove unused property current_power_w
This is no longer supported by home assistanrt. See:
https://github.com/home-assistant/core/issues/53317

remove unused switch property current_power_w

---

custom_components/ocpp/api.py
requirements.txt
tests/test_charge_point.py

Fix blocking warning

---

custom_components/ocpp/api.py

Improve measurand logic

---

custom_components/ocpp/api.py

Instead of disabling authorization for start_transaction initiated via HA user, use a random generated tag and authorize it to start transaction.
This PR started as the following code was not disabling authorization on ABB charger:
```python
resp = await self.get_configuration(ckey.authorize_remote_tx_requests.value)
if resp is True:
await self.configure(ckey.authorize_remote_tx_requests.value, "false")
```
I presume it is due to comparison between `resp` and `True` (is `resp` a string?). 
However, we don't even have to disable authorization in this case. It is sufficient to generate a random tag on initialization and use it for such transactions.

Generate random tagId used to start transaction from UI

---

custom_components/ocpp/api.py

Spec seems to allow for empty list in GetConfiguration response in addition to the list being absent.
Fixes #1293 (together with #1278 )

Check for empty list in GetConfiguration response

---

.coveragerc
setup.cfg

@lbbrhzn I don't think branch testing is working properly with the asyncio tests

Set branch coverage to false

---

custom_components/ocpp/api.py
tests/test_charge_point.py

fixes #1323 https://github.com/mobilityhouse/ocpp/issues/661

fix empty value

---

.github/workflows/constraints.txt
.github/workflows/tests.yaml
requirements.txt

Reduces install requirements from 50s down to 14s

switch to uv from pip

---

custom_components/ocpp/sensor.py

fixes #1403 partially by giving a device class for reactive power sensors.
There is no device class for reactive energy so far, means this cannot be fixed and does not have a device class assigned on purpose: https://developers.home-assistant.io/docs/core/entity/sensor/
Once HA provides a device class for it it can be added here...

Correct reactive power device class

---

custom_components/ocpp/manifest.json

Home Assistant now pip installs version 2.0.0 of ocpp, which breaks the integration. I think this is because 2.0.0 was released on pip today: https://pypi.org/project/ocpp/#history
I see you're working on a version that uses ocpp 2.0.0 - until then, I think it makes sense to have a version that pins to 1.0.0.

Pin ocpp to version 1.0.0

---

docs/support.md

As suggeted in #1425 added an FAQ section to the support page.

add FAQ to support page

---

tests/test_config_flow.py

From HA 2025.1 the constants have been removed

Update to use FlowResultType enums

---

custom_components/ocpp/const.py
custom_components/ocpp/sensor.py
tests/test_charge_point_v16.py
tests/test_init.py
tests/test_sensor.py

After explicitly switching to reactive power device class I missed the state_class also depending on this device_class (#1417).
Should fix https://github.com/lbbrhzn/ocpp/issues/1449 (the raised repair regarding the changed unit of measurement is expected nevertheless)

Fix missing state class for reactive power sensors after #1417

---

custom_components/ocpp/manifest.json
custom_components/ocpp/ocppv201.py
requirements.txt
tests/test_charge_point_v201.py

Fixes #1444, fixes #1402, fixes #1371, fixes #1461

Update to ocpp 2.0.0 to fix blocking

---

custom_components/ocpp/button.py
custom_components/ocpp/number.py
custom_components/ocpp/sensor.py
custom_components/ocpp/switch.py

remove via device from platforms
