README.md, custom_components/ocpp/sensor.py, custom_components/ocpp/services.yaml
Hi, I have forked your repo and added some additional functionality and checks to prevent errors eg TriggerMessage is only sent if supported. However I am stuck at trying to add services to HA, eg to start and stop the charger. Do you have any experience with this, as I'd appreciate some help.
=> ocpp: extend HA integration

custom_components/ocpp/sensor.py
sorry one last one to fix up OR syntax
=> ocpp: fix or syntax

custom_components/ocpp/central_system.py, custom_components/ocpp/const.py, custom_components/ocpp/sensor.py
add a switch to represent the charge point and provide an easy means to start and stop charging
add device information
=> add switch and device information

custom_components/ocpp/api.py, custom_components/ocpp/switch.py
=> fix issue with on_stop_transaction, and linting

custom_components/ocpp/api.py
There were some linting errors on the main branch, which i tried to fix.
=> fix linting errors

custom_components/ocpp/api.py
=> ocpp: revise approach to measurand metrics reading

custom_components/ocpp/config_flow.py
=> Revert "ocpp: bug fix in measurands schema in #57"

.github/workflows/tests.yaml, custom_components/ocpp/api.py, custom_components/ocpp/enums.py, custom_components/ocpp/services.yaml, setup.cfg, tests/conftest.py, tests/const.py, tests/test_charge_point.py, tests/test_switch.py
@lbbrhzn, Combines the previous pull requests, adds custom services and testing of the bulk of api.py.  Should close #51 and #56
=> ocpp: significant repo update

custom_components/ocpp/api.py
=> 101 improve phase processing

custom_components/ocpp/number.py
@lbbrhzn, I'd already done some work on this. Feel free to amend. Fixes #133
=> Update Number platform

custom_components/ocpp/api.py
=> Set ping_timeout to None

custom_components/ocpp/api.py
To help if HA/charger has a network error when starting
=> Change Reset switch to hard reset, trigger post_connect on boot and reset reconnects

custom_components/ocpp/api.py
=> use config_validation on services

custom_components/ocpp/api.py
Short delay added to avoid race condition with boot notification message on first connection/boot
=> Add sleep delay in post connect

custom_components/ocpp/api.py
Should fix #169 but will need testing @eogmau, context also added to metrics to separate charging metrics from clock sampled ones
=> Add context to metrics, fix single phase voltage

custom_components/ocpp/api.py, requirements_test.txt, tests/conftest.py, tests/const.py, tests/test_charge_point.py
=> update tests to work with sockets

custom_components/ocpp/sensor.py
=> derive sensor unit_of_measurement from device_class

custom_components/ocpp/api.py
in api.py, the process_phases should sum power and energy values reported for different phases.
=> sum all reported energy and power phases

custom_components/ocpp/api.py
allow single line neutral values of any phase
=> improve process_phases

custom_components/ocpp/api.py, requirements_test.txt
another attempt to fix the mess...
=> Improve process phases

tests/test_charge_point.py
Test added to confirm averaging works as it should
=> Test for non-zero voltage average

custom_components/ocpp/number.py
Looks like issue was due to mixin order
=> Fix number unavailability

custom_components/ocpp/sensor.py
As System category does not show on device card
=> switch HAChargerDetails to Diagnostic category

custom_components/ocpp/api.py
prevent an exception when connection is closed, due to _connection set to None.
=> prevent exception at close

custom_components/ocpp/number.py
@lbbrhzn not sure if this will help but as we push api changes turning off polling might help
=> Slider unavailable workaround

custom_components/ocpp/api.py, custom_components/ocpp/enums.py, custom_components/ocpp/sensor.py
this my attempt on solving the ping buildup.
=> monitor connection, close on timeout

custom_components/ocpp/api.py, custom_components/ocpp/enums.py, custom_components/ocpp/sensor.py
Upon reconnect, make sure the old connection is closed before we start using the new connection
=> Close old connection before switching to new

.devcontainer/configuration.yaml, custom_components/ocpp/api.py
removing websocket.id from logging, since it results in errors on some ha setups
=> Remove websocket.id

.coveragerc, .github/workflows/tests.yaml
add third party code coverage action, for better insight into code coverage
=> add codecov action

custom_components/ocpp/translations/de.json
I translated the "i-default.json" file to german. Hopefully you have any use for that.
My first pull request ever, hopefully I did all things right ^^
Greetings
Daniel
=> Adding a German translation

requirements_test.txt
@lbbrhzn should fix mqtt paho error
=> bump pytest-homeassistant-custom-component

.devcontainer/configuration.yaml, custom_components/ocpp/__init__.py, custom_components/ocpp/api.py, custom_components/ocpp/const.py
Add support for authorization list in configuration.yaml.
Example:
```yaml
ocpp:
default_authorization_status : 'Invalid'
authorization_list: 
- id_tag : '123456789'
name:  'accepted tag'
authorization_states: 'Accepted'
- id_tag : '987654321'
name: 'expired tag'
authorization_status: 'Expired'
- id_tag : '987654321'
name: 'blocked tag'
authorization_status: 'Blocked'
```
=> add authorization list

custom_components/ocpp/api.py
* perform authorization in both Authorize and StartTransaction
* add more logging
=> improve authorization

docs/user-guide.md
Here's my first Pull Request for the User Guide, so hopefully I've got everything correct.
Wallbox Pulsar Plus has an improved list of entities and I've added a list for the EVBox Elvi.  I plan to add more as owners turn up in the repo and look as though they may be willing to contribute.
Many thanks for all your support so far.
=> User guide update

docs/supported-devices.md
=> Update new device

custom_components/ocpp/sensor.py
=> fix pf unit error

custom_components/ocpp/api.py
Should help with chargers that don't support setting charger availability see #510 or websocket ping #442
=> improve post connect logic

custom_components/ocpp/button.py, custom_components/ocpp/const.py, custom_components/ocpp/number.py, custom_components/ocpp/sensor.py, custom_components/ocpp/switch.py, requirements.txt, requirements_dev.txt, requirements_test.txt, setup.cfg
Looks like I missed this one in #666
=> Naming tidy ups

.github/workflows/constraints.txt, .pre-commit-config.yaml
bump isort to 5.11.5, to solve issue: https://github.com/PyCQA/isort/pull/2078
=> bump isort to 5.11.5

custom_components/ocpp/enums.py
Format for IntFlag changed from 3.10 to 3.11
=> Revert to str repr

custom_components/ocpp/manifest.json, requirements_dev.txt, requirements_test.txt
Following fix in latest MobilityHouse ocpp release, added myself to manifest as additional codeowner
=> revert jsonschema changes

docs/supported-devices.md
=> ABB Terra AC W22-T-0 added to supported-devices

custom_components/ocpp/api.py, custom_components/ocpp/number.py, custom_components/ocpp/switch.py
=> Fix deprecated constants

custom_components/ocpp/api.py, custom_components/ocpp/enums.py
Fix Profiles showing as an Int in frontend
=> Fix Profiles

custom_components/ocpp/api.py
=> Extra logic if measurand not accepted

custom_components/ocpp/sensor.py
=> Remove scaling from sensors

.github/workflows/tests.yaml
=> update codecov action

custom_components/ocpp/const.py
=> Remove ocpp hertz unit

custom_components/ocpp/exception.py, setup.cfg
reintroduce exception.py
adjust flake settings to allow empty file
=> fix exception during setup due to missing exception.py

custom_components/ocpp/manifest.json
@lbbrhzn , I should have updated these in the deprecation fix!
=> Update dep versions

custom_components/ocpp/api.py, tests/test_charge_point.py
Reverts lbbrhzn/ocpp#1198
See https://github.com/mobilityhouse/ocpp/pull/652 for upstream fix
=> Revert "Fix blocking warning"

custom_components/ocpp/__init__.py
improve robustness when the integration is unloaded
=> improve unload robustness

.devcontainer.json, requirements.txt
bump pytest-homeassistant-custom-component to 0.13.148
=> bump python version in devcontainer to 3.12

custom_components/ocpp/api.py, tests/test_charge_point.py
=> Improve get feature error handling

custom_components/ocpp/api.py, tests/test_charge_point.py
=> add try except for getting measurands

custom_components/ocpp/api.py
=> fix missing n phase

.github/workflows/constraints.txt, .pre-commit-config.yaml, .ruff.toml, .vscode/settings.json, custom_components/ocpp/api.py, custom_components/ocpp/button.py, custom_components/ocpp/config_flow.py, custom_components/ocpp/const.py, custom_components/ocpp/enums.py, custom_components/ocpp/exception.py, custom_components/ocpp/number.py, custom_components/ocpp/sensor.py, custom_components/ocpp/switch.py, docs/conf.py, manage/update_manifest.py, tests/conftest.py, tests/const.py, tests/test_charge_point.py, tests/test_config_flow.py, tests/test_init.py
use ruff for linting and formatting
includes fixes for ruff linting errors
includes updates setting for visual studio code
=> use ruff in pre-commit for linting and formatting

custom_components/ocpp/translations/de.json
=> Add missing DE translations

custom_components/ocpp/api.py
See https://developers.home-assistant.io/docs/asyncio_blocking_operations/
=> add executor to ssl to avoid blocking

custom_components/ocpp/const.py
Fix for:
https://github.com/lbbrhzn/ocpp/issues/1559
=> Fix temperature unit
